SET_DIR=set
SEN_DIR=sentinel
DYN_DIR=dynamic
LINK_DIR=link

BIN=sentinel_func sentinel_struc dynamic_struc link_struc 

CC=gcc
CPPFLAGS=-I ${SET_DIR} -I ${SEN_DIR} -I ${DYN_DIR} -I{LINK_DIR}
CFLAGS=-Wall -Wextra -std=c99

all: test

build: ${BIN}

test: ${BIN}
	@for e in ${BIN}; do \
	echo $${e}; ./$${e}; \
	done

clean:
	rm -f *.o ${BIN}

#sentinel
set_sentinel.o: ${SEN_DIR}/set_sentinel.c ${SEN_DIR}/set_sentinel.h
	${CC} ${CPPFLAGS} ${CFLAGS} ${SEN_DIR}/set_sentinel.c -c

test_sentinel_struc.o: ${SEN_DIR}/test_sentinel_struc.c ${SEN_DIR}/set_sentinel.h
	${CC} ${CPPFLAGS} ${CFLAGS} ${SEN_DIR}/test_sentinel_struc.c -c

test_sentinel_func.o: ${SET_DIR}/test_set_func.c ${SEN_DIR}/set_sentinel.h
	${CC} ${CPPFLAGS} ${CFLAGS} -DSENTINEL ${SET_DIR}/test_set_func.c -c -o $@

sentinel_func: test_sentinel_func.o set_sentinel.o
	${CC} test_sentinel_func.o set_sentinel.o -o $@

sentinel_struc: test_sentinel_struc.o set_sentinel.o
	${CC} test_sentinel_struc.o set_sentinel.o -o $@


#dynamic

set_dynamic.o:	${DYN_DIR}/set_dynamic.c ${DYN_DIR}/set_dynamic.h
	${CC} ${CPPFLAGS} ${CFLAGS} ${DYN_DIR}/set_dynamic.c -c

test_dynamic_struc.o: ${DYN_DIR}/test_dynamic_struc.c ${DYN_DIR}/set_dynamic.h
	${CC} ${CPPFLAGS} ${CFLAGS} ${DYN_DIR}/test_dynamic_struc.c -c

dynamic_struc:	test_dynamic_struc.o set_dynamic.o
	${CC} test_dynamic_struc.o set_dynamic.o -o $@

test_dynamic_func.o: ${DYN_DIR}/test_dynamic_func.c ${DYN_DIR}/set_dynamic.h
	${CC} ${CPPFLAGS} ${CFLAGS} ${DYN_DIR}/test_dynamic_func.c -c

dynamic_func:	test_dynamic_func.o set_dynamic.o
	${CC} test_dynamic_func.o set_dynamic.o -o $@

#link

set_link.o:	${LINK_DIR}/set_link.c ${LINK_DIR}/set_link.h
	${CC} ${CPPFLAGS} ${CFLAGS} ${LINK_DIR}/set_link.c -c

link.o:	${LINK_DIR}/link.c ${LINK_DIR}/link.h
	${CC} ${CPPFLAGS} ${CFLAGS} ${LINK_DIR}/link.c -c

test_link_struc.o:	${LINK_DIR}/test_link_struc.c ${LINK_DIR}/link.h
		${CC} ${CPPFLAGS} ${CFLAGS} ${LINK_DIR}/test_link_struc.c -c

link_struc:	test_link_struc.o link.o set_link.o
		${CC} test_link_struc.o link.o -o $@

test_link_func.o:	${LINK_DIR}/test_link_func.c ${LINK_DIR}/link.h
		${CC} ${CPPFLAGS} ${CFLAGS} ${LINK_DIR}/test_link_func.c -c

link_func:	test_link_func.o
		${CC} test_link_struc.o -o $@



set_func:	${SET_DIR}/test_set_func.c ${LINK_DIR}/set_link.c ${LINK_DIR}/set_link.h
